# Generated by Django 4.2.5 on 2024-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='account_type',
            field=models.TextField(max_length=20),
        ),
    ]
