# Generated by Django 4.2.5 on 2024-01-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_alter_accountapplication_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='account_type',
            field=models.CharField(max_length=50),
        ),
    ]
